name = "sre-of-me"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "sre-of-me-db"
database_id = "8c93200e-c8a0-40c7-acba-e87f15c36ccd"
